import Head from 'next/head';
import { About } from '../components/about';
import { Hero } from '../components/hero';
import Layout from '../components/layout';
import { Mantra } from '../components/mantra';
import Projects from '../components/projects';
import { Terminal } from '../components/terminal';
import Project from '../interfaces/project';
import { getAllProjects } from '../lib/api';
import { RadialGradient } from '../styles/Hero.styled';

type Props = {
  allProjects: Project[];
};

export default function Home({ allProjects }: Props) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RadialGradient />
      <Hero />
      <Terminal />
      <Projects allProjects={allProjects} />
      <About />
      <Mantra />
    </Layout>
  );
}

export async function getStaticProps() {
  const allProjects = getAllProjects([
    'slug',
    'title',
    'githubCode',
    'livePreview',
    'date',
    'coverImage',
    'transitionImage',
    'subTitle',
  ]);

  return {
    props: {
      allProjects,
    },
  };
}
