import type { NextPage } from 'next';
import Head from 'next/head';
import { Hero } from '../components/hero';
import Layout from '../components/layout';
import Projects from '../components/projects';
import { Terminal } from '../components/terminal';
import { RadialGradient } from '../styles/Hero.styled';

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RadialGradient />
      <Hero />
      <Terminal />
      <Projects />
    </Layout>
  );
};

export default Home;
